### ISSUE TITLE
Use international date format

### ISSUE THREAD

**Issue by midasi** [OnyxfireInc/OnyxBackupVM#18]
Currently OnyxBackup is using US date format (mm/dd/yyyy).

It would be great if you would add an option or completely switch to the international date format according to ISO 8601 to increase readability.

Some examples: 

Date in the debug log:
Current: 04/06/2020 02:47:41 PM - INFO: Started: 14:47:41 [ service:_print_function_header():753 ]
Desired: 2020-04-06 14:47:41 - INFO: Started: 14:47:41 [ service:_print_function_header():753 ]

Date in the backup filename:
Current: backup_04062020-142011.xva (i.e. ddmmyyyy or 6th April 2020)
Desired: backup_20200406-142011.xva (i.e. yyyymmdd)

**Comment by lancefogle** [comment]
I will work to get this switched over to ISO 8601 soon and push an update to resolve this. We are US based and that is the reason behind the date format currently in use however I see no issue with changing this format.

This will however affect anyone who uses SIEM or something to consume their logs as they will have configured it likely to parse the timestamp on the logs. I will note this change in the change log though so they should be aware before updating.

**Comment by midasi** [comment]
That's great, thank you! We actually use SIEM as well, that's why we try to implement the SysLogHandler and switch to a syslog-like message format (see as well feature request #19)
