### ISSUE TITLE
Log file per host and date

### ISSUE THREAD

**Issue by midasi** [OnyxfireInc/OnyxBackupVM#19]
We would like to have a log file per host and date instead of a general log file for all hosts.

Current: onyxbackup.log / debug.log
Desired: onyxbackup-[hostname]-[yyyymmdd].log / debug-[hostname]-[yyyymmdd].log

We didn't find a way to configure that in logging.json.

**Comment by lancefogle** [comment]
The code does not inject the hostname at the time of building the logging configuration, however, you can easily have a separate logging config file (like logging.json) for each scheduled/executed run of the program by using the LOG_CFG environment variable. You could then just have a separate file with your preferred filename for the host you are targeting with that run. You could change the below lines like the example I below in the logging config file
```
"file": {
     ...
    "filename": '/path/to/logs/onyxbackup-myhostname.log'),
    ...
},
"debug": {
    ...
    "filename": '/path/to/logs/debug-myhostname.log'),
    ...
}
```

As for the dates on the filenames, that is not possible with a logging.json file as this is a static file. You could however use the "TimedRotatingFileHandler" on the class line of the config file for each of those handlers to make all files rotate each day and append the date however you like to previous days' runs.

That is outside the scope of this application but that is why I gave flexibility to use custom logging.json files for each run using the environment variable LOG_CFG (i.e. LOG_CFG=/path/to/custom-logging.json

See the following documentation to help you configure it as you like: https://docs.python.org/3/library/logging.handlers.html#timedrotatingfilehandler

**Comment by midasi** [comment]
Thank you for the hint with the LOG_CFG variable. I thought to use the SysLogHandler instead and splitting the files with rsyslog. Do you have experience with this handler and the required syslog message format?

**Comment by lancefogle** [comment]
That same link I sent you has all the filehandlers and their documentation. Read through the section on the SysLogHandler and it should help you get what you want to achieve.

If you don't want to go through creating several separate log files, the script by default config outputs everything to the console as well (std.out) so you could simply redirect the script output to any file you want. If you do that, you can append timestamps pretty easily.

Your crontab entry could look like the following:
```
10 0 * * 6 <OnyxBackupVM path>/onyxbackup-vm.py -c /path/to/myhostname.config -l debug > /path/to/logs/onyxbackup-myhostname-`date +%y%m%d` 2>&1
```

or even:
```
10 0 * * 6 <OnyxBackupVM path>/onyxbackup-vm.py -c /path/to/myhostname.config -l debug > /path/to/logs/onyxbackup-`hostname`-`date +%Y%m%d` 2>&1
```

**Comment by lancefogle** [comment]
For SysLogHandler, it uses the time.strftime() in python to format the time. You just have to pass it a datefmt parameter when creating the logger handler that formats it based on the format for time.strftime().

Something like `%Y%m%d %H:%M:%S` would give you the format you are looking for I think.

See the links below for documentation:
https://docs.python.org/3/library/logging.html#formatter-objects
https://docs.python.org/3/library/time.html#time.strftime

**Comment by lancefogle** [comment]
I am closing this issue as I have provided many possible solutions and all of which will work with the existing code. I will still be updating the default format as mention in #18 but otherwise this issue does not require any further code changes.

Thanks for your request/questions as I am sure this information might help others coming in search of it.

**Comment by midasi** [comment]
Thanks for the feedback. All proposed solutions including SysLogHandler work perfectly fine!
Here is the logging configuration snippet in case someone else is interested in using syslog:
    "syslog": {
      "class": "logging.handlers.SysLogHandler",
      "level": "INFO",
      "address": "/dev/log",
      "facility": "user"
    }
